# Enterprise knowledge discovery platform configuration

# Enterprise GPT Configuration
openai:
  api_key: "${ENTERPRISE_GPT_API_KEY}"
  organization_id: "${ENTERPRISE_ORGANIZATION_ID}"
  base_url: "https://api.openai.com/v1"
  default_model: "gpt-4o"
  max_tokens: 4000
  temperature: 0.7
  timeout: 60

# Phase 3 & 4 Advanced Configuration
advanced_features:
  # Multi-Source Orchestration (Phase 3)
  source_orchestration:
    enabled: true
    cross_platform_search: true
    content_fusion: true
    cross_referencing: true
    intelligent_ranking: true
    diversity_threshold: 0.3
    fusion_similarity_threshold: 0.7
    max_fusion_operations: 3
  
  # Proactive Knowledge Management (Phase 4)
  proactive_management:
    enabled: true
    predictive_caching: true
    lifecycle_monitoring: true
    gap_detection: true
    auto_recommendations: true
    auto_organization: true
    
    # Predictive caching settings
    predictive_cache:
      enabled: true
      prediction_interval_minutes: 5
      cache_expiry_hours: 2
      confidence_threshold: 0.3
      max_predictions: 50
    
    # Content lifecycle settings
    lifecycle_monitoring:
      enabled: true
      monitoring_interval_hours: 1
      freshness_threshold_days: 90
      outdated_threshold_days: 365
      unused_threshold_days: 180
    
    # Knowledge gap detection
    gap_detection:
      enabled: true
      detection_interval_minutes: 30
      min_failed_queries: 3
      confidence_threshold: 0.6
      gap_types:
        - "missing_documentation"
        - "outdated_content"
        - "inconsistent_information"
        - "incomplete_coverage"
    
    # Auto-organization
    auto_organization:
      enabled: true
      organization_interval_hours: 3
      auto_tagging: true
      hierarchy_optimization: true
      relationship_mapping: true

# Memory Layer Configuration (Phase 2 Enhanced)
memory:
  enabled: true
  database_path: "data/navo_memory.db"
  max_memory_entries: 100000
  cleanup_interval_hours: 24
  retention_days: 365
  
  # Memory types
  episodic_memory:
    enabled: true
    max_episodes: 10000
    retention_days: 90
  
  semantic_memory:
    enabled: true
    max_concepts: 50000
    similarity_threshold: 0.8
  
  procedural_memory:
    enabled: true
    max_procedures: 5000
    success_threshold: 0.7

# Reasoning Engine Configuration (Phase 2 Enhanced)
reasoning:
  enabled: true
  reasoning_model: "gpt-4o"
  max_reasoning_steps: 5
  confidence_threshold: 0.6
  
  # Reasoning types
  analytical_reasoning:
    enabled: true
    depth_level: 3
  
  predictive_reasoning:
    enabled: true
    prediction_horizon_days: 30
  
  diagnostic_reasoning:
    enabled: true
    root_cause_analysis: true
  
  prescriptive_reasoning:
    enabled: true
    recommendation_confidence: 0.7
  
  comparative_reasoning:
    enabled: true
    comparison_threshold: 0.5

# Integration Settings (Enhanced)
integrations:
  confluence:
    enabled: true
    base_url: "${CONFLUENCE_BASE_URL}"
    username: "${CONFLUENCE_USERNAME}"
    api_token: "${CONFLUENCE_API_TOKEN}"
    # Enterprise spaces for engineering teams
    spaces_to_sync:
      - "ENG"        # Engineering documentation
      - "DOCS"       # General documentation
      - "RUNBOOKS"   # Operational runbooks and SOPs
      - "ONBOARD"    # Onboarding materials and guides
      - "PROTOCOLS"  # Testing protocols and procedures
      - "APIS"       # API documentation and versioning
    spaces_to_exclude:
      - "ARCHIVE"    # Archived content
      - "TEMP"       # Temporary workspace
      - "DRAFT"      # Draft content
    content_types:
      - "page"
      - "blogpost"
    max_results_per_request: 50
    sync_attachments: true
    max_attachment_size_mb: 10
    extract_custom_fields: true
    respect_permissions: true
    # Enterprise content tracking
    track_freshness: true
    flag_outdated_content: true
    outdated_threshold_days: 90
    # Phase 3 enhancements
    enable_cross_referencing: true
    content_priority: "high"
    sync_frequency_hours: 6

  sharepoint:
    enabled: true
    tenant_id: "${SHAREPOINT_TENANT_ID}"
    client_id: "${SHAREPOINT_CLIENT_ID}"
    client_secret: "${SHAREPOINT_CLIENT_SECRET}"
    site_url: "https://yourcompany.sharepoint.com/sites/engineering"
    document_libraries:
      - "Documents"
      - "Engineering"
      - "Procedures"
      - "Knowledge Base"
    max_results_per_request: 50
    sync_file_types:
      - "docx"
      - "pdf"
      - "pptx"
      - "xlsx"
      - "md"
    max_file_size_mb: 25
    respect_permissions: true
    track_freshness: true
    # Phase 3 enhancements
    enable_cross_referencing: true
    content_priority: "high"
    sync_frequency_hours: 6

# Application Settings (Enhanced)
app:
  name: "NAVO"
  version: "2.0.0"
  description: "Navigate + Ops - Enterprise Knowledge Discovery Platform"
  host: "${HOST:-0.0.0.0}"
  port: ${PORT:-8000}
  debug: false
  log_level: "INFO"
  cors_origins:
    - "https://yourcompany.com"
    - "https://teams.microsoft.com"
  
  # Phase 3 & 4 features
  features:
    multi_source_orchestration: true
    proactive_management: true
    predictive_caching: true
    content_lifecycle: true
    knowledge_gaps: true
    auto_recommendations: true
    real_time_websockets: true
    advanced_analytics: true

# Cache Configuration (Enhanced)
cache:
  redis_url: "${REDIS_URL}"
  default_ttl: 3600
  max_memory: "512mb"
  key_prefix: "navo:"
  
  # Multi-level caching
  levels:
    l1_memory:
      enabled: true
      max_size: 1000
      ttl: 300
    
    l2_redis:
      enabled: true
      ttl: 3600
    
    l3_predictive:
      enabled: true
      ttl: 7200
      max_entries: 10000

# Security Settings (Enhanced)
security:
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 3600
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  
  # Advanced security
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
  
  audit_logging:
    enabled: true
    log_level: "INFO"
    retention_days: 365
    include_query_content: false  # For privacy

# Query Processing (Enhanced)
query:
  max_length: 1000
  response_timeout: 30
  enable_context_enhancement: true
  enable_freshness_tracking: true
  similarity_threshold: 0.7
  
  # Phase 3 enhancements
  cross_platform_search: true
  intelligent_ranking: true
  content_fusion: true
  diversity_enforcement: true
  
  # Phase 4 enhancements
  predictive_suggestions: true
  proactive_recommendations: true
  gap_detection: true

<<<<<<< HEAD
# MS Teams Integration
=======
# Microsoft Teams Integration (Enhanced)
>>>>>>> 4c2379d (🚀 Phase 3 & 4 Complete: Production-Ready Enterprise Knowledge Orchestration Platform)
teams:
  webhook_url: "${TEAMS_WEBHOOK_URL:-}"
  adaptive_cards_enabled: true
  mention_support: true
  max_card_actions: 5
  
  # Phase 3 & 4 features
  proactive_notifications: true
  lifecycle_alerts: true
  recommendation_cards: true

# Monitoring and Analytics (Enhanced)
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  log_queries: true
  track_performance: true
  retention_days: 30
  
  # Advanced monitoring
  performance_tracking:
    enabled: true
    track_response_times: true
    track_accuracy: true
    track_user_satisfaction: true
  
  analytics:
    enabled: true
    user_behavior_tracking: true
    content_performance_tracking: true
    predictive_analytics: true
  
  alerting:
    enabled: true
    performance_threshold_ms: 5000
    error_rate_threshold: 0.05
    notification_channels:
      - "email"
      - "teams"

# Database Configuration
database:
  # Primary database for application data
  primary:
    type: "postgresql"  # or "sqlite" for development
    host: "${DB_HOST:-localhost}"
    port: ${DB_PORT:-5432}
    database: "${DB_NAME:-navo}"
    username: "${DB_USERNAME:-navo}"
    password: "${DB_PASSWORD}"
    pool_size: 10
    max_overflow: 20
  
  # Memory database for fast access
  memory:
    type: "sqlite"
    path: "data/navo_memory.db"
    
  # Analytics database
  analytics:
    type: "postgresql"
    host: "${ANALYTICS_DB_HOST:-localhost}"
    port: ${ANALYTICS_DB_PORT:-5432}
    database: "${ANALYTICS_DB_NAME:-navo_analytics}"
    username: "${ANALYTICS_DB_USERNAME:-navo_analytics}"
    password: "${ANALYTICS_DB_PASSWORD}"

# Backup and Recovery
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  storage_type: "s3"  # or "local"
  s3_bucket: "${BACKUP_S3_BUCKET}"
  encryption: true

# Performance Tuning
performance:
  # Connection pooling
  connection_pools:
    database: 20
    redis: 10
    http: 50
  
  # Async settings
  async_workers: 4
  max_concurrent_requests: 100
  
  # Memory management
  max_memory_usage_mb: 2048
  gc_threshold: 0.8
  
  # Caching optimization
  cache_warming: true
  preload_common_queries: true

