# Enterprise knowledge discovery platform configuration

# Enterprise GPT Configuration
openai:
  api_key: "${ENTERPRISE_GPT_API_KEY}"
  organization_id: "${ENTERPRISE_ORGANIZATION_ID}"
  base_url: "https://api.openai.com/v1"
  default_model: "gpt-4o"
  max_tokens: 4000
  temperature: 0.7
  timeout: 60

# Integration Settings
integrations:
  confluence:
    enabled: true
    base_url: "${CONFLUENCE_BASE_URL}"
    username: "${CONFLUENCE_USERNAME}"
    api_token: "${CONFLUENCE_API_TOKEN}"
    # Enterprise spaces for engineering teams
    spaces_to_sync:
      - "ENG"        # Engineering documentation
      - "DOCS"       # General documentation
      - "RUNBOOKS"   # Operational runbooks and SOPs
      - "ONBOARD"    # Onboarding materials and guides
      - "PROTOCOLS"  # Testing protocols and procedures
      - "APIS"       # API documentation and versioning
    spaces_to_exclude:
      - "ARCHIVE"    # Archived content
      - "TEMP"       # Temporary workspace
      - "DRAFT"      # Draft content
    content_types:
      - "page"
      - "blogpost"
    max_results_per_request: 50
    sync_attachments: true
    max_attachment_size_mb: 10
    extract_custom_fields: true
    respect_permissions: true
    # Enterprise content tracking
    track_freshness: true
    flag_outdated_content: true
    outdated_threshold_days: 90

  sharepoint:
    enabled: true
    tenant_id: "${SHAREPOINT_TENANT_ID}"
    client_id: "${SHAREPOINT_CLIENT_ID}"
    client_secret: "${SHAREPOINT_CLIENT_SECRET}"
    site_url: "https://yourcompany.sharepoint.com/sites/engineering"
    document_libraries:
      - "Documents"
      - "Engineering"
      - "Procedures"
      - "Knowledge Base"
    max_results_per_request: 50
    sync_file_types:
      - "docx"
      - "pdf"
      - "pptx"
      - "xlsx"
      - "md"
    max_file_size_mb: 25
    respect_permissions: true
    track_freshness: true

# Application Settings
app:
  name: "NAVO"
  version: "2.0.0"
  description: "Navigate + Ops - Enterprise Knowledge Discovery Platform"
  host: "${HOST:-0.0.0.0}"
  port: ${PORT:-8000}
  debug: false
  log_level: "INFO"
  cors_origins:
    - "https://yourcompany.com"
    - "https://teams.microsoft.com"

# Cache Configuration
cache:
  redis_url: "${REDIS_URL}"
  default_ttl: 3600
  max_memory: "256mb"
  key_prefix: "navo:"

# Security Settings
security:
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 3600
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Query Processing
query:
  max_length: 1000
  response_timeout: 30
  enable_context_enhancement: true
  enable_freshness_tracking: true
  similarity_threshold: 0.7

# Microsoft Teams Integration
teams:
  webhook_url: "${TEAMS_WEBHOOK_URL:-}"
  adaptive_cards_enabled: true
  mention_support: true
  max_card_actions: 5

# Monitoring and Analytics
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  log_queries: true
  track_performance: true
  retention_days: 30

